Feat/get recommendation
lamchiminhmark/ObieLocal pull request #25
Opened 2020-05-28 08:44 UTC by lamchiminhmark

Created and tested logic for creating and combining recommendation in frontend

2020-05-28 17:57 UTC, Cpotter2 requested changes
Looks good! Just had a couple questions -- see comments.

2020-05-28 17:57 UTC, Cpotter2 commented on src/actions/recommenderActions.js
> +    return fetch('/rateEvent', requestOptions)
@lamchiminhmark Does returning the fetch call here actually ever dispatch an action to Redux? Or are you not attempting to dispatch an action?

2020-05-28 17:57 UTC, Cpotter2 commented on src/components/Sidepane/EventDetails.js
> +    //TODO: Get real userId
@knguyend   Can this now be updated with Firestore access to the real uid? (so we can get rid of this TODO?)

2020-05-29 09:36 UTC, lamchiminhmark commented
Closing PR and opening new one where problems are addressed

2020-05-29 09:37 UTC, closed without merging